apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../../annugame
  # - ../../aocbot
  # - ../../aoch
  - ../../archive
  # - ../../areafiftylan
  # - ../../areafiftylan-legacy
  - ../../adminer
  # - ../../bt-website
  - ../../chipcie-bapc-2025
  # - ../../chipcie-legacy
  # - ../../chipcie-nwerc-2022
  # - ../../chipcie-nwerc-2023
  # - ../../chipcie-nwerc-2024
  - ../../chipcie-website
  - ../../chipcie-static-scoreboard
  - ../../choice
  - ../../chpay
  - ../../cod
  # - ../../connect
  - ../../dienst2
  - ../../events
  # - ../../flitcie
  # - ../../hackdelft
  - ../../iap-testapp-spring
  - ../../keycloak
  - ../../listmonk
  - ../../narrowcast-content
  - ../../passes
  - ../../mand
  - ../../shuttr
  - ../../varnish-proxy
  - ../../website
  - ../../wiki
