apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aocbot.yaml
  - aoch.yaml
  - areafiftylan-legacy.yaml
  - chpay.yaml
  - chpay-mail.yaml
  - connect.yaml
  - connect-proxy.yaml
  - dienst2.yaml
  - dienst2-service-account.yaml
  - discord-webhook.yaml
  - events.yaml
  - github-webhook.yaml
  - iap.yaml
  - keycloak.yaml
  - listmonk.yaml
  - mail.yaml
  - mand.yaml
  - narrowcast-content.yaml
  - passes.yaml
  - passes-keys.yaml
  - postgres.yaml
  - postgres-keycloak.yaml
  - shuttr.yaml
